2020-04-23 08:47:53.313  INFO 14184 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 14184 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 08:47:53.325  INFO 14184 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 08:47:58.439  INFO 14184 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 08:47:58.526  INFO 14184 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 46ms. Found 0 repository interfaces.
2020-04-23 08:47:59.382  INFO 14184 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a21bb17a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 08:47:59.956  INFO 14184 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 08:47:59.978  INFO 14184 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 08:47:59.978  INFO 14184 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 08:48:00.161  INFO 14184 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 08:48:00.161  INFO 14184 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6209 ms
2020-04-23 08:48:02.056  INFO 14184 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 08:48:02.469  INFO 14184 --- [cluster-ClusterId{value='5ea0e5c1c7bcca3768727dd1', description='null'}-localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:4}] to localhost:27017
2020-04-23 08:48:02.485  INFO 14184 --- [cluster-ClusterId{value='5ea0e5c1c7bcca3768727dd1', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 5]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2442500}
2020-04-23 08:48:04.137  INFO 14184 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 08:48:04.906  WARN 14184 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 08:48:05.331  INFO 14184 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 08:48:05.344  INFO 14184 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 13.839 seconds (JVM running for 16.475)
2020-04-23 08:48:24.233  INFO 14184 --- [http-nio-6666-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 08:48:24.234  INFO 14184 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 08:48:24.243  INFO 14184 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 9 ms
2020-04-23 08:48:24.321  INFO 14184 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 08:48:24
2020-04-23 08:48:24.321  INFO 14184 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 08:48:24.335  INFO 14184 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 08:48:24.657  INFO 14184 --- [http-nio-6666-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 08:48:26.379  INFO 14184 --- [http-nio-6666-exec-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:5}] to localhost:27017
2020-04-23 08:48:26.744 ERROR 14184 --- [http-nio-6666-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at com.hcdz.hk.impl.BehaviorServiceImpl.getAlarmInformation(BehaviorServiceImpl.java:110) ~[classes/:na]
	at com.hcdz.hk.impl.BehaviorServiceImpl$$FastClassBySpringCGLIB$$7fb8b90.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at com.hcdz.hk.impl.BehaviorServiceImpl$$EnhancerBySpringCGLIB$$67034c6c.getAlarmInformation(<generated>) ~[classes/:na]
	at com.hcdz.hk.controller.AlarmController.getAlarmInformation(AlarmController.java:98) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

2020-04-23 08:49:49.698  INFO 4784 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 4784 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 08:49:49.702  INFO 4784 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 08:49:50.469  INFO 4784 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 08:49:50.484  INFO 4784 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11ms. Found 0 repository interfaces.
2020-04-23 08:49:50.733  INFO 4784 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$d2cd724e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 08:49:50.958  INFO 4784 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 08:49:50.978  INFO 4784 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 08:49:50.978  INFO 4784 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 08:49:51.104  INFO 4784 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 08:49:51.104  INFO 4784 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1349 ms
2020-04-23 08:49:52.065  INFO 4784 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 08:49:52.155  INFO 4784 --- [cluster-ClusterId{value='5ea0e630c7bcca12b02c99c6', description='null'}-localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:6}] to localhost:27017
2020-04-23 08:49:52.159  INFO 4784 --- [cluster-ClusterId{value='5ea0e630c7bcca12b02c99c6', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 5]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2558400}
2020-04-23 08:49:52.511  INFO 4784 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 08:49:52.782  WARN 4784 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 08:49:52.976  INFO 4784 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 08:49:52.979  INFO 4784 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.721 seconds (JVM running for 4.784)
2020-04-23 08:49:57.702  INFO 4784 --- [http-nio-6666-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 08:49:57.702  INFO 4784 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 08:49:57.709  INFO 4784 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2020-04-23 08:49:57.757  INFO 4784 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 08:49:57
2020-04-23 08:49:57.757  INFO 4784 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 08:49:57.757  INFO 4784 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 08:49:57.851  INFO 4784 --- [http-nio-6666-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 08:49:58.130  INFO 4784 --- [http-nio-6666-exec-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:7}] to localhost:27017
2020-04-23 08:49:58.154 ERROR 4784 --- [http-nio-6666-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at com.hcdz.hk.impl.BehaviorServiceImpl.getAlarmInformation(BehaviorServiceImpl.java:110) ~[classes/:na]
	at com.hcdz.hk.impl.BehaviorServiceImpl$$FastClassBySpringCGLIB$$7fb8b90.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at com.hcdz.hk.impl.BehaviorServiceImpl$$EnhancerBySpringCGLIB$$7e332311.getAlarmInformation(<generated>) ~[classes/:na]
	at com.hcdz.hk.controller.AlarmController.getAlarmInformation(AlarmController.java:98) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.24.jar:9.0.24]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

2020-04-23 09:01:37.941  INFO 12876 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 12876 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 09:01:37.944  INFO 12876 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 09:01:38.730  INFO 12876 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 09:01:38.745  INFO 12876 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11ms. Found 0 repository interfaces.
2020-04-23 09:01:38.995  INFO 12876 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$2cdf0cd2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 09:01:39.201  INFO 12876 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 09:01:39.220  INFO 12876 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 09:01:39.220  INFO 12876 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 09:01:39.359  INFO 12876 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 09:01:39.359  INFO 12876 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1368 ms
2020-04-23 09:01:40.324  INFO 12876 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 09:01:40.415  INFO 12876 --- [cluster-ClusterId{value='5ea0e8f4c7bcca324ceda917', description='null'}-localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:8}] to localhost:27017
2020-04-23 09:01:40.420  INFO 12876 --- [cluster-ClusterId{value='5ea0e8f4c7bcca324ceda917', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 5]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=3031100}
2020-04-23 09:01:40.779  INFO 12876 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 09:01:41.046  WARN 12876 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 09:01:41.238  INFO 12876 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 09:01:41.240  INFO 12876 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.743 seconds (JVM running for 4.783)
2020-04-23 09:01:56.085  INFO 12876 --- [http-nio-6666-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 09:01:56.086  INFO 12876 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 09:01:56.093  INFO 12876 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2020-04-23 09:01:56.127  INFO 12876 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 09:01:56
2020-04-23 09:01:56.127  INFO 12876 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 09:01:56.127  INFO 12876 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 09:01:56.227  INFO 12876 --- [http-nio-6666-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 09:01:56.493  INFO 12876 --- [http-nio-6666-exec-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:9}] to localhost:27017
2020-04-23 09:01:56.508  INFO 12876 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 入库失败
2020-04-23 09:08:11.152  INFO 7352 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 7352 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 09:08:11.156  INFO 7352 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 09:08:11.927  INFO 7352 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 09:08:11.942  INFO 7352 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11ms. Found 0 repository interfaces.
2020-04-23 09:08:12.190  INFO 7352 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$1e4d1dcd] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 09:08:12.403  INFO 7352 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 09:08:12.422  INFO 7352 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 09:08:12.423  INFO 7352 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 09:08:12.555  INFO 7352 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 09:08:12.555  INFO 7352 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1351 ms
2020-04-23 09:08:13.523  INFO 7352 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 09:08:13.617  INFO 7352 --- [cluster-ClusterId{value='5ea0ea7dc7bcca1cb858812a', description='null'}-localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:10}] to localhost:27017
2020-04-23 09:08:13.620  INFO 7352 --- [cluster-ClusterId{value='5ea0ea7dc7bcca1cb858812a', description='null'}-localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 5]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2225600}
2020-04-23 09:08:13.980  INFO 7352 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 09:08:14.254  WARN 7352 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 09:08:14.449  INFO 7352 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 09:08:14.452  INFO 7352 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.809 seconds (JVM running for 4.919)
2020-04-23 09:08:17.944  INFO 7352 --- [http-nio-6666-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 09:08:17.944  INFO 7352 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 09:08:17.949  INFO 7352 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2020-04-23 09:08:17.976  INFO 7352 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 09:08:17
2020-04-23 09:08:17.976  INFO 7352 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 09:08:17.976  INFO 7352 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 09:08:18.057  INFO 7352 --- [http-nio-6666-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 09:08:18.319  INFO 7352 --- [http-nio-6666-exec-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:11}] to localhost:27017
2020-04-23 09:08:18.332  INFO 7352 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 入库失败
2020-04-23 09:08:40.843  INFO 7352 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 09:08:40
2020-04-23 09:08:40.843  INFO 7352 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   1
2020-04-23 09:08:40.844  INFO 7352 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 09:08:40.856  INFO 7352 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 入库失败
2020-04-23 16:47:49.494  INFO 18412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 18412 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:47:49.536  INFO 18412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:47:54.303  INFO 18412 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:47:54.364  INFO 18412 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 25ms. Found 0 repository interfaces.
2020-04-23 16:47:55.348  INFO 18412 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$b41b4946] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:47:55.918  INFO 18412 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:47:55.945  INFO 18412 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:47:55.945  INFO 18412 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:47:56.142  INFO 18412 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:47:56.143  INFO 18412 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6160 ms
2020-04-23 16:47:57.881  INFO 18412 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:47:58.258  INFO 18412 --- [cluster-ClusterId{value='5ea1563dc7bcca47ec6bfca3', description='null'}-127.0.0.1:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:16}] to 127.0.0.1:27017
2020-04-23 16:47:58.262  INFO 18412 --- [cluster-ClusterId{value='5ea1563dc7bcca47ec6bfca3', description='null'}-127.0.0.1:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 2, 5]}, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2171400}
2020-04-23 16:48:00.326  INFO 18412 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:48:01.134  WARN 18412 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 16:48:01.440  INFO 18412 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 16:48:01.455  INFO 18412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 13.657 seconds (JVM running for 15.201)
2020-04-23 16:48:36.055  INFO 18164 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 18164 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:48:36.058  INFO 18164 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:48:36.795  INFO 18164 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:48:36.815  INFO 18164 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15ms. Found 0 repository interfaces.
2020-04-23 16:48:37.077  INFO 18164 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$5f6c32f4] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:48:37.290  INFO 18164 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:48:37.311  INFO 18164 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:48:37.312  INFO 18164 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:48:37.463  INFO 18164 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:48:37.463  INFO 18164 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1337 ms
2020-04-23 16:48:38.446  INFO 18164 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:48:38.557  INFO 18164 --- [cluster-ClusterId{value='5ea15666c7bcca46f4e2f714', description='null'}-192.168.0.238:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:5}] to 192.168.0.238:27017
2020-04-23 16:48:38.563  INFO 18164 --- [cluster-ClusterId{value='5ea15666c7bcca46f4e2f714', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.0.238:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 6]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=3418600}
2020-04-23 16:48:38.937  INFO 18164 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:48:39.214  WARN 18164 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 16:48:39.418  INFO 18164 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 16:48:39.421  INFO 18164 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.906 seconds (JVM running for 4.913)
2020-04-23 16:48:56.940  INFO 18164 --- [http-nio-6666-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 16:48:56.940  INFO 18164 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 16:48:56.949  INFO 18164 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 9 ms
2020-04-23 16:48:57.029  INFO 18164 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:48:57
2020-04-23 16:48:57.030  INFO 18164 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 16:48:57.030  INFO 18164 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:48:57.292  INFO 18164 --- [http-nio-6666-exec-2] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 16:48:58.898  INFO 18164 --- [http-nio-6666-exec-2] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:6}] to 192.168.0.238:27017
2020-04-23 16:48:59.106  INFO 18164 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 入库成功
2020-04-23 16:50:41.295  INFO 13380 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 13380 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:50:41.299  INFO 13380 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:50:42.092  INFO 13380 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:50:42.108  INFO 13380 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 12ms. Found 0 repository interfaces.
2020-04-23 16:50:42.367  INFO 13380 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$358067b2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:50:42.614  INFO 13380 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:50:42.633  INFO 13380 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:50:42.633  INFO 13380 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:50:42.767  INFO 13380 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:50:42.767  INFO 13380 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1415 ms
2020-04-23 16:50:43.736  INFO 13380 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:50:43.838  INFO 13380 --- [cluster-ClusterId{value='5ea156e3c7bcca3444ec2b52', description='null'}-192.168.0.238:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:7}] to 192.168.0.238:27017
2020-04-23 16:50:43.843  INFO 13380 --- [cluster-ClusterId{value='5ea156e3c7bcca3444ec2b52', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.0.238:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 6]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=2839400}
2020-04-23 16:50:44.191  INFO 13380 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:50:44.269  WARN 13380 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-04-23 16:50:44.269  INFO 13380 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-04-23 16:50:44.273  INFO 13380 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-23 16:50:44.290  INFO 13380 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-23 16:50:44.295 ERROR 13380 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2020-04-23 16:51:18.469  INFO 11304 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 11304 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:51:18.472  INFO 11304 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:51:19.201  INFO 11304 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:51:19.216  INFO 11304 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2020-04-23 16:51:19.469  INFO 11304 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$b1ea2c39] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:51:19.666  INFO 11304 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:51:19.685  INFO 11304 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:51:19.685  INFO 11304 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:51:19.815  INFO 11304 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:51:19.815  INFO 11304 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1235 ms
2020-04-23 16:51:20.805  INFO 11304 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:51:20.942  INFO 11304 --- [cluster-ClusterId{value='5ea15708c7bcca2c28aecc62', description='null'}-192.168.0.238:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:8}] to 192.168.0.238:27017
2020-04-23 16:51:20.947  INFO 11304 --- [cluster-ClusterId{value='5ea15708c7bcca2c28aecc62', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.0.238:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 6]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=3503300}
2020-04-23 16:51:21.294  INFO 11304 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:51:21.569  WARN 11304 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 16:51:21.779  INFO 11304 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 16:51:21.782  INFO 11304 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.948 seconds (JVM running for 5.001)
2020-04-23 16:51:45.570  INFO 11304 --- [http-nio-6666-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 16:51:45.571  INFO 11304 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 16:51:45.577  INFO 11304 --- [http-nio-6666-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2020-04-23 16:51:45.609  INFO 11304 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:51:45
2020-04-23 16:51:45.609  INFO 11304 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 16:51:45.609  INFO 11304 --- [http-nio-6666-exec-1] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:51:45.694  INFO 11304 --- [http-nio-6666-exec-1] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 16:51:50.412 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:51:54.748 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:51:59.503 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:04.326 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:09.246 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:14.191 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:18.979 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:20.096  INFO 11304 --- [http-nio-6666-exec-3] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:52:20
2020-04-23 16:52:20.096  INFO 11304 --- [http-nio-6666-exec-3] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   1
2020-04-23 16:52:20.096  INFO 11304 --- [http-nio-6666-exec-3] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:52:23.910 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:28.922 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:33.812 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:38.617 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:43.744 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:44.774  INFO 11304 --- [http-nio-6666-exec-5] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:52:44
2020-04-23 16:52:44.774  INFO 11304 --- [http-nio-6666-exec-5] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   2
2020-04-23 16:52:44.774  INFO 11304 --- [http-nio-6666-exec-5] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:52:48.790 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:53.568 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:52:58.417 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:53:03.402 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:53:08.506 ERROR 11304 --- [Druid-ConnectionPool-Create-1233092490] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:mysql://192.168.0.238:3306/hhsep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636) ~[druid-1.1.12.jar:1.1.12]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505) ~[druid-1.1.12.jar:1.1.12]
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'192.168.0.9' (using password: YES)
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:795) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:720) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:688) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:130) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:540) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:163) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:841) ~[mysql-connector-java-8.0.17.jar:8.0.17]
	... 7 common frames omitted

2020-04-23 16:53:12.878  INFO 15372 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 15372 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:53:12.881  INFO 15372 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:53:13.532  INFO 15372 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:53:13.547  INFO 15372 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11ms. Found 0 repository interfaces.
2020-04-23 16:53:13.794  INFO 15372 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$86db462d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:53:14.009  INFO 15372 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:53:14.030  INFO 15372 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:53:14.030  INFO 15372 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:53:14.229  INFO 15372 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:53:14.230  INFO 15372 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1304 ms
2020-04-23 16:53:15.205  INFO 15372 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:53:15.391  INFO 15372 --- [cluster-ClusterId{value='5ea1577bc7bcca3c0cf9486e', description='null'}-192.168.0.238:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:12}] to 192.168.0.238:27017
2020-04-23 16:53:15.396  INFO 15372 --- [cluster-ClusterId{value='5ea1577bc7bcca3c0cf9486e', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.0.238:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 6]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=3215400}
2020-04-23 16:53:15.662  INFO 15372 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:53:15.946  WARN 15372 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 16:53:16.143  INFO 15372 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 16:53:16.145  INFO 15372 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.839 seconds (JVM running for 4.869)
2020-04-23 16:53:20.007  INFO 15372 --- [http-nio-6666-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 16:53:20.007  INFO 15372 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 16:53:20.014  INFO 15372 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2020-04-23 16:53:20.046  INFO 15372 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:53:20
2020-04-23 16:53:20.047  INFO 15372 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 16:53:20.047  INFO 15372 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:53:20.143  INFO 15372 --- [http-nio-6666-exec-2] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 16:53:20.619  INFO 15372 --- [http-nio-6666-exec-2] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:13}] to 192.168.0.238:27017
2020-04-23 16:53:20.719  INFO 15372 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 入库成功
2020-04-23 16:55:38.859  INFO 18284 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 18284 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 16:55:38.863  INFO 18284 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 16:55:39.530  INFO 18284 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 16:55:39.545  INFO 18284 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 12ms. Found 0 repository interfaces.
2020-04-23 16:55:39.801  INFO 18284 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$533e1c5b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 16:55:40.016  INFO 18284 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 16:55:40.036  INFO 18284 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 16:55:40.037  INFO 18284 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 16:55:40.161  INFO 18284 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 16:55:40.161  INFO 18284 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1242 ms
2020-04-23 16:55:41.124  INFO 18284 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 16:55:41.255  INFO 18284 --- [cluster-ClusterId{value='5ea1580dc7bcca476c7a03f5', description='null'}-192.168.0.238:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:14}] to 192.168.0.238:27017
2020-04-23 16:55:41.264  INFO 18284 --- [cluster-ClusterId{value='5ea1580dc7bcca476c7a03f5', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=192.168.0.238:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 6]}, minWireVersion=0, maxWireVersion=3, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=7730800}
2020-04-23 16:55:41.579  INFO 18284 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 16:55:41.856  WARN 18284 --- [main] c.b.m.core.metadata.TableInfoHelper      : Warn: Could not find @TableId in Class: com.hcdz.hk.entity.GridSchool.
2020-04-23 16:55:42.050  INFO 18284 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 16:55:42.052  INFO 18284 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.805 seconds (JVM running for 4.868)
2020-04-23 16:55:48.376  INFO 18284 --- [http-nio-6666-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-23 16:55:48.377  INFO 18284 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-23 16:55:48.384  INFO 18284 --- [http-nio-6666-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2020-04-23 16:55:48.418  INFO 18284 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求时间----->>>>>   2020-04-23 16:55:48
2020-04-23 16:55:48.419  INFO 18284 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 接受请求次数----->>>>>   0
2020-04-23 16:55:48.419  INFO 18284 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 事件报文：{"method":"OnEventNotify","params":{"ability":"event_face_match","events":[{"data":{"alarmResult":[{"faces":[{"URL":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","age":{"ageGroup":"young","range":0,"value":255},"faceExpression":{"value":""},"faceId":336126,"faceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"faceScore":2,"gender":{"value":"male"},"glass":{"value":"no"},"recommendFaceRect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129},"smile":{"value":"no"},"stayDuration":0}],"image":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037462272000046912&size=46912","targetAttrs":{"bkgUrl":"http://192.168.3.229:80/picture/Streaming/tracks/103/?name=ch0001_00000004351037467033600434715&size=434715","cameraIndexCode":"44c21fea0001459ab40bfa4842026dc6","deviceId":"44c21fea0001459ab40bfa4842026dc6","deviceIndexCode":"71fb6d30995042f590ba2120477610fc","faceTime":"2020-04-01T10:46:22.000+08:00","imageServerCode":"","rect":{"height":0.083999998867511749,"width":0.048000000417232513,"x":0.087999999523162842,"y":0.21799999475479129}},"traceIdx":336126,"traceUuid":"B54759A3-04A4-4EED-97E0-CB9E130647E6"}],"channelID":33,"dataType":"faceMatch","dateTime":"2020-04-01T10:46:22.000+08:00","eventDescription":"alarmResult","eventType":"alarmResult","ipAddress":"192.168.3.229","portNo":8000,"recvTime":"2020-04-01T10:45:48.737+08:00","sendTime":"2020-04-01T10:45:48.739+08:00"},"eventId":"276F5258-8934-4EB5-B849-32E4D5A1E1D5","eventType":131659,"happenTime":"2020-04-01T10:46:22.000+08:00","srcIndex":"44c21fea0001459ab40bfa4842026dc6","srcParentIndex":"71fb6d30995042f590ba2120477610fc","srcType":"camera","status":0,"timeout":0}],"sendTime":"2020-04-01T10:45:48.740+08:00"}}
2020-04-23 16:55:48.521  INFO 18284 --- [http-nio-6666-exec-2] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} inited
2020-04-23 16:55:49.019  INFO 18284 --- [http-nio-6666-exec-2] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:15}] to 192.168.0.238:27017
2020-04-23 16:55:49.118  INFO 18284 --- [http-nio-6666-exec-2] com.hcdz.hk.controller.AlarmController   : 入库成功
2020-04-23 17:18:45.066  INFO 13508 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 13508 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 17:18:45.069  INFO 13508 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 17:18:45.816  INFO 13508 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 17:18:45.833  INFO 13508 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 12ms. Found 0 repository interfaces.
2020-04-23 17:18:45.916  WARN 13508 --- [main] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.hcdz.hk]' package. Please check your configuration.
2020-04-23 17:18:46.093  INFO 13508 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a21bb17a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 17:18:46.304  INFO 13508 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 17:18:46.324  INFO 13508 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 17:18:46.325  INFO 13508 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 17:18:46.582  INFO 13508 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 17:18:46.583  INFO 13508 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1460 ms
2020-04-23 17:18:47.574  INFO 13508 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 17:18:48.075  INFO 13508 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 17:18:48.154  WARN 13508 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-04-23 17:18:48.155  INFO 13508 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-04-23 17:18:48.160  INFO 13508 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-23 17:18:48.176  INFO 13508 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-23 17:18:48.182 ERROR 13508 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2020-04-23 17:20:13.244  INFO 12392 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 12392 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 17:20:13.249  INFO 12392 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 17:20:13.884  INFO 12392 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 17:20:13.898  INFO 12392 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2020-04-23 17:20:13.973  WARN 12392 --- [main] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.hcdz.hk]' package. Please check your configuration.
2020-04-23 17:20:14.146  INFO 12392 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a379188d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 17:20:14.363  INFO 12392 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 17:20:14.384  INFO 12392 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 17:20:14.384  INFO 12392 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 17:20:14.548  INFO 12392 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 17:20:14.548  INFO 12392 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1242 ms
2020-04-23 17:20:15.532  INFO 12392 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 17:20:16.002  INFO 12392 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 17:20:16.083  WARN 12392 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-04-23 17:20:16.083  INFO 12392 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-04-23 17:20:16.087  INFO 12392 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-23 17:20:16.103  INFO 12392 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-23 17:20:16.110 ERROR 12392 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2020-04-23 17:24:11.356  INFO 7304 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 7304 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 17:24:11.360  INFO 7304 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 17:24:12.118  INFO 7304 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 17:24:12.132  INFO 7304 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2020-04-23 17:24:12.207  WARN 7304 --- [main] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.hcdz.hk]' package. Please check your configuration.
2020-04-23 17:24:12.380  INFO 7304 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$dcb64ab4] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 17:24:12.595  INFO 7304 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 17:24:12.618  INFO 7304 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 17:24:12.618  INFO 7304 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 17:24:12.754  INFO 7304 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 17:24:12.754  INFO 7304 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1346 ms
2020-04-23 17:24:13.750  INFO 7304 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 17:24:14.216  INFO 7304 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 17:24:14.295  WARN 7304 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-04-23 17:24:14.295  INFO 7304 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-04-23 17:24:14.299  INFO 7304 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-23 17:24:14.315  INFO 7304 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-23 17:24:14.320 ERROR 7304 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2020-04-23 17:25:06.141  INFO 17216 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 17216 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 17:25:06.145  INFO 17216 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 17:25:06.812  INFO 17216 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 17:25:06.830  INFO 17216 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14ms. Found 0 repository interfaces.
2020-04-23 17:25:07.050  INFO 17216 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$8e473666] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-04-23 17:25:07.398  INFO 17216 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 17:25:07.427  INFO 17216 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 17:25:07.428  INFO 17216 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 17:25:07.547  INFO 17216 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 17:25:07.547  INFO 17216 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1349 ms
2020-04-23 17:25:08.603  INFO 17216 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 17:25:09.055  INFO 17216 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 17:25:09.133  WARN 17216 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
2020-04-23 17:25:09.134  INFO 17216 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-04-23 17:25:09.138  INFO 17216 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-23 17:25:09.155  INFO 17216 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-23 17:25:09.160 ERROR 17216 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

2020-04-23 17:26:00.249  INFO 2412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Starting HkWarningserviceApplication on DESKTOP-IPDL43K with PID 2412 (D:\zglkafka\zz\hkEvent\hk-warningservice\target\classes started by CR7 in D:\zglkafka\zz\hkEvent)
2020-04-23 17:26:00.252  INFO 2412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : No active profile set, falling back to default profiles: default
2020-04-23 17:26:00.937  INFO 2412 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-04-23 17:26:00.955  INFO 2412 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 15ms. Found 0 repository interfaces.
2020-04-23 17:26:01.368  INFO 2412 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 6666 (http)
2020-04-23 17:26:01.386  INFO 2412 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-04-23 17:26:01.386  INFO 2412 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.24]
2020-04-23 17:26:01.579  INFO 2412 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-04-23 17:26:01.580  INFO 2412 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1270 ms
2020-04-23 17:26:02.557  INFO 2412 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[192.168.0.238:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-23 17:26:02.969  INFO 2412 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-23 17:26:03.117  INFO 2412 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 6666 (http) with context path ''
2020-04-23 17:26:03.119  INFO 2412 --- [main] com.hcdz.hk.HkWarningserviceApplication  : Started HkWarningserviceApplication in 3.37 seconds (JVM running for 4.351)
2020-04-23 17:26:22.589  INFO 2412 --- [cluster-ClusterId{value='5ea15f2ac7bcca096cd3a0c2', description='null'}-192.168.0.238:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server 192.168.0.238:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_181]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

